import type { ResearchNode } from "./research.js";

/**
 * research-tree.ts — PLAN.md 8.6: the actual ±100 simpul. One data literal, no logic (validation
 * lives in `unlocks.ts`/`packages/sim`). 5 cabang, kedalaman 0–4 — depth doubles as the pita
 * kedalaman `tools/balance-lab` measures against (PLAN.md 8.8), so it is a balance axis, not
 * decoration.
 *
 * Structure notes (see docs/ADR/0009 for the "why"):
 * - Inti (depth 0) is the free starter set — `costData: 0`, `requires: []`. Every other branch's
 *   depth-1 nodes are ALSO `requires: []` (Inti is always completed, so requiring it explicitly
 *   would be a no-op) — a branch entry point costs Data but nothing else.
 * - Every `ConditionKind` and `ActionKind` gets exactly one "base" unlock (an `Unlock` with `tier`
 *   omitted). Actions that are tiered ALSO get 1–2 further nodes that raise the ceiling (`tier: 2`
 *   or `tier: 3` — a threshold, not a per-tier toggle, `research.ts`'s own doc comment). `exploit`
 *   gets the full three-node chain (I -> II -> III) as PLAN.md's own flagship example; every other
 *   tiered action jumps straight from its base (tier 1) to a single `tier: 3` node, which is why
 *   the tree lands near 100 nodes rather than the ±70 first estimate — completeness (one base node
 *   per kind, ~82 of them alone) plus real tier progression for GDD §9 costs more than the original
 *   guess, and that trade favours coverage over hitting the number exactly.
 * - Every `(DefenseNodeType, tier)` pair gets its own node (RULESET.md §14's own completeness
 *   rule) — router is the only untiered placeable node.
 * - Five depth-4 capstones (PLAN.md 8.4/ADR 0007 §C): `alarm` III and `detonate` III (Serbuan),
 *   `spoof-signature` III (Bayangan), `emp-burst` III (Pengintaian), `worm-split` III (Replikasi).
 *   Each requires its own branch's depth-3 node AND one depth-2 node from a DIFFERENT branch, so no
 *   single branch alone reaches every capstone (PLAN.md's "stealth-first vs brute-first" tension).
 */

export const RESEARCH_TREE: readonly ResearchNode[] = [
  // --- Inti (abu-abu) — depth 0, gratis, prasyarat: tidak ada ---
  {
    id: "inti.move-toward-core",
    branch: "inti",
    depth: 0,
    name: "Jalan ke Core",
    summary: "Jalur terpendek berbobot jarak ke Core. Setiap virus butuh tepat satu aksi gerak.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "action", action: "move-toward-core" }],
  },
  {
    id: "inti.hold-position",
    branch: "inti",
    depth: 0,
    name: "Diam di Tempat",
    summary: "Menahan slot gerak tick ini — dasar dari setiap sheet yang bereaksi sebelum melangkah.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "action", action: "hold-position" }],
  },
  {
    id: "inti.at-node",
    branch: "inti",
    depth: 0,
    name: "Sedang di Node",
    summary: "Kondisi paling dasar: berdiri di node, bukan menyeberang edge.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "condition", condition: "at-node" }],
  },
  {
    id: "inti.node-here-is",
    branch: "inti",
    depth: 0,
    name: "Node Saat Ini",
    summary: "Membaca tipe node yang sedang diduduki virus.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "condition", condition: "node-here-is" }],
  },
  {
    id: "inti.on-breach-node",
    branch: "inti",
    depth: 0,
    name: "Di Atas Breach Node",
    summary: "Membaca apakah virus sedang menduduki Firewall hidup atau Core.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "condition", condition: "on-breach-node" }],
  },
  {
    id: "inti.integrity-below",
    branch: "inti",
    depth: 0,
    name: "Integrity di Bawah X%",
    summary: "Membaca sisa Integrity virus sendiri terhadap ambang.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "condition", condition: "integrity-below" }],
  },
  {
    id: "inti.brute-force",
    branch: "inti",
    depth: 0,
    name: "Brute Force",
    summary: "Damage per tick ke Breach Node yang diduduki — serangan paling dasar.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "action", action: "brute-force" }],
  },
  {
    id: "inti.set-flag",
    branch: "inti",
    depth: 0,
    name: "Nyalakan/Matikan Penanda",
    summary: "Menulis salah satu dari 4 penanda milik tubuh — sheet jadi punya ingatan.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "action", action: "set-flag" }],
  },
  {
    id: "inti.flag-is",
    branch: "inti",
    depth: 0,
    name: "Penanda N Menyala",
    summary: "Membaca penanda yang ditulis Nyalakan/Matikan Penanda.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "condition", condition: "flag-is" }],
  },
  {
    id: "inti.router",
    branch: "inti",
    depth: 0,
    name: "Router",
    summary: "Penghubung pasif tanpa efek combat — kerangka tiap denah pertahanan.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "router" }],
  },
  {
    id: "inti.firewall.1",
    branch: "inti",
    depth: 0,
    name: "Firewall Tier I",
    summary: "Breach Node paling dasar — balas damage ke virus yang mendudukinya.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "firewall", tier: 1 }],
  },
  {
    id: "inti.honeypot.1",
    branch: "inti",
    depth: 0,
    name: "Honeypot Tier I",
    summary: "Jebakan sekali pakai — mematikan virus yang masuk tanpa mendeteksinya lebih dulu.",
    costData: 0,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "honeypot", tier: 1 }],
  },

  // --- Serbuan (merah) — serangan langsung ---
  {
    id: "serbuan.exploit.1",
    branch: "serbuan",
    depth: 1,
    name: "Exploit Tier I",
    summary: "Damage one-shot besar pada tick pertama di sebuah node.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "exploit" }],
  },
  {
    id: "serbuan.exploit.2",
    branch: "serbuan",
    depth: 2,
    name: "Exploit Tier II",
    summary: "Exploit yang lebih dalam — one-shot lebih besar per node.",
    costData: 400,
    requires: ["serbuan.exploit.1"],
    unlocks: [{ kind: "action", action: "exploit", tier: 2 }],
  },
  {
    id: "serbuan.exploit.3",
    branch: "serbuan",
    depth: 3,
    name: "Exploit Tier III",
    summary: "Exploit puncak — flagship tier-up: satu blok, tiga simpul, tiga tingkat kekuatan.",
    costData: 900,
    requires: ["serbuan.exploit.2"],
    unlocks: [{ kind: "action", action: "exploit", tier: 3 }],
  },
  {
    id: "serbuan.overload.1",
    branch: "serbuan",
    depth: 1,
    name: "Overload Tier I",
    summary: "Splash damage ke Breach Node tetangga saat sebuah Breach Node hancur.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "overload" }],
  },
  {
    id: "serbuan.overload.3",
    branch: "serbuan",
    depth: 2,
    name: "Overload Tier III",
    summary: "Splash lebih besar, radius lebih lebar.",
    costData: 400,
    requires: ["serbuan.overload.1"],
    unlocks: [{ kind: "action", action: "overload", tier: 3 }],
  },
  {
    id: "serbuan.siphon.1",
    branch: "serbuan",
    depth: 1,
    name: "Sedot Data Tier I",
    summary: "Memulihkan Integrity dari damage serang yang tubuh ini hasilkan sendiri.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "siphon" }],
  },
  {
    id: "serbuan.siphon.3",
    branch: "serbuan",
    depth: 2,
    name: "Sedot Data Tier III",
    summary: "Proporsi heal yang lebih besar dari damage yang dihasilkan.",
    costData: 400,
    requires: ["serbuan.siphon.1"],
    unlocks: [{ kind: "action", action: "siphon", tier: 3 }],
  },
  {
    id: "serbuan.sprint.1",
    branch: "serbuan",
    depth: 1,
    name: "Lari Tier I",
    summary: "Tick ini: lebih cepat, dengan biaya Integrity.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "sprint" }],
  },
  {
    id: "serbuan.sprint.3",
    branch: "serbuan",
    depth: 2,
    name: "Lari Tier III",
    summary: "Lonjakan speed terbesar, biaya Integrity per tick paling tinggi.",
    costData: 400,
    requires: ["serbuan.sprint.1"],
    unlocks: [{ kind: "action", action: "sprint", tier: 3 }],
  },
  {
    id: "serbuan.brute-force.3",
    branch: "serbuan",
    depth: 2,
    name: "Brute Force Tier III",
    summary: "Menaikkan Brute Force dasar (Inti) sampai tier III.",
    costData: 400,
    requires: ["inti.brute-force"],
    unlocks: [{ kind: "action", action: "brute-force", tier: 3 }],
  },
  {
    id: "serbuan.core-within-hops",
    branch: "serbuan",
    depth: 1,
    name: "Core ≤ X Hop",
    summary: "Membaca jarak ke Core dalam hop — tahu kapan serbuan tinggal selangkah lagi.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "core-within-hops" }],
  },
  {
    id: "serbuan.core-hp-below",
    branch: "serbuan",
    depth: 1,
    name: "HP Core < X%",
    summary: "Membaca sisa HP Core — tahu kapan mengganti taktik jadi all-in.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "core-hp-below" }],
  },
  {
    id: "serbuan.node-hp-below",
    branch: "serbuan",
    depth: 2,
    name: "HP Node Ini < X%",
    summary: "Membaca sisa HP Breach Node yang sedang diduduki.",
    costData: 400,
    requires: ["serbuan.core-hp-below"],
    unlocks: [{ kind: "condition", condition: "node-hp-below" }],
  },
  {
    id: "serbuan.target-strike.1",
    branch: "serbuan",
    depth: 2,
    name: "Serang Node Pendukung Tier I",
    summary: "Damage ke node pendukung hidup terdekat dalam 1 hop (ICE Sentry, Scanner, dst).",
    costData: 400,
    requires: ["serbuan.exploit.1"],
    unlocks: [{ kind: "action", action: "target-strike" }],
  },
  {
    id: "serbuan.target-strike.3",
    branch: "serbuan",
    depth: 3,
    name: "Serang Node Pendukung Tier III",
    summary: "Damage per tick ke node pendukung jauh lebih besar.",
    costData: 900,
    requires: ["serbuan.target-strike.1"],
    unlocks: [{ kind: "action", action: "target-strike", tier: 3 }],
  },
  {
    id: "serbuan.overclock.1",
    branch: "serbuan",
    depth: 2,
    name: "Overclock Tier I",
    summary: "Selama 20 tick: semua damage serang naik, ICE lebih akurat ke tubuh ini.",
    costData: 400,
    requires: ["serbuan.exploit.1"],
    unlocks: [{ kind: "action", action: "overclock" }],
  },
  {
    id: "serbuan.overclock.3",
    branch: "serbuan",
    depth: 3,
    name: "Overclock Tier III",
    summary: "Multiplier damage tertinggi yang Overclock bisa berikan.",
    costData: 900,
    requires: ["serbuan.overclock.1"],
    unlocks: [{ kind: "action", action: "overclock", tier: 3 }],
  },
  {
    id: "serbuan.detonate.1",
    branch: "serbuan",
    depth: 3,
    name: "Detonasi Tier I",
    summary: "Mengorbankan seluruh sisa Integrity sebagai damage ke Breach Node, lalu mati.",
    costData: 900,
    requires: ["serbuan.target-strike.1"],
    unlocks: [{ kind: "action", action: "detonate" }],
  },
  {
    id: "serbuan.detonate.3",
    branch: "serbuan",
    depth: 4,
    name: "Detonasi Tier III — capstone",
    summary: "Multiplier pengorbanan tertinggi. Butuh pengalaman kabur (Bayangan) untuk tahu kapan benar-benar tidak ada jalan lain.",
    costData: 1800,
    requires: ["serbuan.detonate.1", "bayangan.purge.1"],
    unlocks: [{ kind: "action", action: "detonate", tier: 3 }],
  },
  {
    id: "serbuan.firewall.2",
    branch: "serbuan",
    depth: 1,
    name: "Firewall Tier II",
    summary: "HP dan balasan damage lebih tinggi dari tier I.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "firewall", tier: 2 }],
  },
  {
    id: "serbuan.firewall.3",
    branch: "serbuan",
    depth: 2,
    name: "Firewall Tier III",
    summary: "Firewall paling keras — butuh Attack blok sungguhan untuk ditembus.",
    costData: 400,
    requires: ["serbuan.firewall.2"],
    unlocks: [{ kind: "defense-node", node: "firewall", tier: 3 }],
  },
  {
    id: "serbuan.alarm.1",
    branch: "serbuan",
    depth: 2,
    name: "Alarm Relay Tier I",
    summary: "Sekali per battle: menyalakan siaga jaringan — semua ICE Sentry lebih cepat & akurat.",
    costData: 400,
    requires: ["serbuan.firewall.2"],
    unlocks: [{ kind: "defense-node", node: "alarm", tier: 1 }],
  },
  {
    id: "serbuan.alarm.2",
    branch: "serbuan",
    depth: 3,
    name: "Alarm Relay Tier II",
    summary: "Radius trigger lebih luas, siaga bertahan lebih lama.",
    costData: 900,
    requires: ["serbuan.alarm.1"],
    unlocks: [{ kind: "defense-node", node: "alarm", tier: 2 }],
  },
  {
    id: "serbuan.alarm.3",
    branch: "serbuan",
    depth: 4,
    name: "Alarm Relay Tier III — capstone",
    summary: "Siaga jaringan terpanjang dan terluas. Butuh pemahaman replikasi (Replikasi) untuk tahu kapan lawan sebenarnya lebih dari satu tubuh.",
    costData: 1800,
    requires: ["serbuan.alarm.2", "replikasi.entity-count-below"],
    unlocks: [{ kind: "defense-node", node: "alarm", tier: 3 }],
  },

  // --- Bayangan (hijau) — siluman & bertahan ---
  {
    id: "bayangan.cloak.1",
    branch: "bayangan",
    depth: 1,
    name: "Cloak Tier I",
    summary: "Kebal status \"scanned\" & bukan target ICE Sentry selama beberapa tick, lalu cooldown.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "cloak" }],
  },
  {
    id: "bayangan.cloak.3",
    branch: "bayangan",
    depth: 2,
    name: "Cloak Tier III",
    summary: "Durasi kebal terlama, radius deteksi Scanner terhadap tubuh ini paling kecil.",
    costData: 400,
    requires: ["bayangan.cloak.1"],
    unlocks: [{ kind: "action", action: "cloak", tier: 3 }],
  },
  {
    id: "bayangan.move-back",
    branch: "bayangan",
    depth: 1,
    name: "Mundur",
    summary: "Balik ke node yang barusan ditinggalkan.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "move-back" }],
  },
  {
    id: "bayangan.arm-decoy.1",
    branch: "bayangan",
    depth: 1,
    name: "Pasang Decoy Tier I",
    summary: "Menyerap satu trigger berikutnya (ICE, Honeypot, Trap).",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "arm-decoy" }],
  },
  {
    id: "bayangan.arm-decoy.3",
    branch: "bayangan",
    depth: 2,
    name: "Pasang Decoy Tier III",
    summary: "Lebih banyak aktivasi, tiap aktivasi menyerap lebih dari satu trigger.",
    costData: 400,
    requires: ["bayangan.arm-decoy.1"],
    unlocks: [{ kind: "action", action: "arm-decoy", tier: 3 }],
  },
  {
    id: "bayangan.slow-crawl.1",
    branch: "bayangan",
    depth: 2,
    name: "Slow Crawl Tier I",
    summary: "Tick ini: lebih pelan, lebih sulit ditembak ICE.",
    costData: 400,
    requires: ["bayangan.cloak.1"],
    unlocks: [{ kind: "action", action: "slow-crawl" }],
  },
  {
    id: "bayangan.slow-crawl.3",
    branch: "bayangan",
    depth: 3,
    name: "Slow Crawl Tier III",
    summary: "Pengurangan akurasi ICE terbesar yang Slow Crawl bisa berikan.",
    costData: 900,
    requires: ["bayangan.slow-crawl.1"],
    unlocks: [{ kind: "action", action: "slow-crawl", tier: 3 }],
  },
  {
    id: "bayangan.purge.1",
    branch: "bayangan",
    depth: 2,
    name: "Bersihkan Tier I",
    summary: "Menghapus status diperlambat (Tarpit & Slow Crawl) untuk sementara.",
    costData: 400,
    requires: ["bayangan.cloak.1"],
    unlocks: [{ kind: "action", action: "purge" }],
  },
  {
    id: "bayangan.purge.3",
    branch: "bayangan",
    depth: 3,
    name: "Bersihkan Tier III",
    summary: "Window imunitas terhadap efek diperlambat paling panjang.",
    costData: 900,
    requires: ["bayangan.purge.1"],
    unlocks: [{ kind: "action", action: "purge", tier: 3 }],
  },
  {
    id: "bayangan.recall",
    branch: "bayangan",
    depth: 2,
    name: "Balik ke Checkpoint",
    summary: "Jalur terpendek ke node checkpoint terakhir.",
    costData: 400,
    requires: ["bayangan.move-back"],
    unlocks: [{ kind: "action", action: "recall" }],
  },
  {
    id: "bayangan.set-checkpoint.1",
    branch: "bayangan",
    depth: 2,
    name: "Pasang Checkpoint Tier I",
    summary: "Merekam node saat ini. Saat mati, hidup lagi sekali di sana.",
    costData: 400,
    requires: ["bayangan.recall"],
    unlocks: [{ kind: "action", action: "set-checkpoint" }],
  },
  {
    id: "bayangan.set-checkpoint.3",
    branch: "bayangan",
    depth: 3,
    name: "Pasang Checkpoint Tier III",
    summary: "Integrity respawn tertinggi, dua jatah respawn per battle.",
    costData: 900,
    requires: ["bayangan.set-checkpoint.1"],
    unlocks: [{ kind: "action", action: "set-checkpoint", tier: 3 }],
  },
  {
    id: "bayangan.spoof-signature.1",
    branch: "bayangan",
    depth: 3,
    name: "Palsukan Tanda Tangan Tier I",
    summary: "Menghapus status \"scanned\" seketika dan menolak scan baru untuk sementara.",
    costData: 900,
    requires: ["bayangan.slow-crawl.1"],
    unlocks: [{ kind: "action", action: "spoof-signature" }],
  },
  {
    id: "bayangan.spoof-signature.3",
    branch: "bayangan",
    depth: 4,
    name: "Palsukan Tanda Tangan Tier III — capstone",
    summary: "Window anti-scan terpanjang. Butuh tahu persis node bertipe apa yang sedang dituju (Pengintaian) untuk memutuskan kapan menyamar.",
    costData: 1800,
    requires: ["bayangan.spoof-signature.1", "pengintaian.move-toward-node-type"],
    unlocks: [{ kind: "action", action: "spoof-signature", tier: 3 }],
  },
  {
    id: "bayangan.honeypot.2",
    branch: "bayangan",
    depth: 1,
    name: "Honeypot Tier II",
    summary: "Menyamar sebagai Core di hasil sensor — butuh sensor tier tinggi untuk tembus.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "honeypot", tier: 2 }],
  },
  {
    id: "bayangan.honeypot.3",
    branch: "bayangan",
    depth: 2,
    name: "Honeypot Tier III",
    summary: "Virus yang sempat men-scan node ini sebelum masuk tetap kena status scanned permanen.",
    costData: 400,
    requires: ["bayangan.honeypot.2"],
    unlocks: [{ kind: "defense-node", node: "honeypot", tier: 3 }],
  },
  {
    id: "bayangan.trap.1",
    branch: "bayangan",
    depth: 1,
    name: "Trap Tier I",
    summary: "Meledak sekali saat node pertama dimasuki, lalu inert.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "trap", tier: 1 }],
  },
  {
    id: "bayangan.trap.2",
    branch: "bayangan",
    depth: 2,
    name: "Trap Tier II",
    summary: "Damage ledakan lebih besar.",
    costData: 400,
    requires: ["bayangan.trap.1"],
    unlocks: [{ kind: "defense-node", node: "trap", tier: 2 }],
  },
  {
    id: "bayangan.trap.3",
    branch: "bayangan",
    depth: 3,
    name: "Trap Tier III",
    summary: "Damage ledakan tertinggi, plus splash ke node tetangga.",
    costData: 900,
    requires: ["bayangan.trap.2"],
    unlocks: [{ kind: "defense-node", node: "trap", tier: 3 }],
  },
  {
    id: "bayangan.tarpit.1",
    branch: "bayangan",
    depth: 1,
    name: "Tarpit Tier I",
    summary: "Memperlambat speed virus dalam radius — tidak menumpuk dengan Tarpit lain.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "tarpit", tier: 1 }],
  },
  {
    id: "bayangan.tarpit.2",
    branch: "bayangan",
    depth: 2,
    name: "Tarpit Tier II",
    summary: "Perlambatan lebih kuat.",
    costData: 400,
    requires: ["bayangan.tarpit.1"],
    unlocks: [{ kind: "defense-node", node: "tarpit", tier: 2 }],
  },
  {
    id: "bayangan.tarpit.3",
    branch: "bayangan",
    depth: 3,
    name: "Tarpit Tier III",
    summary: "Perlambatan terkuat, radius terluas.",
    costData: 900,
    requires: ["bayangan.tarpit.2"],
    unlocks: [{ kind: "defense-node", node: "tarpit", tier: 3 }],
  },

  // --- Pengintaian (kuning) — sensor & informasi ---
  {
    id: "pengintaian.honeypot-near",
    branch: "pengintaian",
    depth: 1,
    name: "Ada Honeypot Dekat",
    summary: "Sensor: Honeypot yang belum terpicu ada dalam radius.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "honeypot-near" }],
  },
  {
    id: "pengintaian.trap-near",
    branch: "pengintaian",
    depth: 1,
    name: "Ada Trap Dekat",
    summary: "Sensor: Trap yang belum meledak ada dalam radius.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "trap-near" }],
  },
  {
    id: "pengintaian.ice-near",
    branch: "pengintaian",
    depth: 1,
    name: "Ada ICE Sentry Dekat",
    summary: "Sensor: ICE Sentry yang masih bisa menembak ada dalam radius.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "ice-near" }],
  },
  {
    id: "pengintaian.scanner-near",
    branch: "pengintaian",
    depth: 1,
    name: "Ada Scanner Dekat",
    summary: "Sensor: Scanner hidup ada dalam radius.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "scanner-near" }],
  },
  {
    id: "pengintaian.node-ahead-is",
    branch: "pengintaian",
    depth: 1,
    name: "Node di Depan =",
    summary: "Membaca tipe node tujuan berikutnya sebelum sampai.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "node-ahead-is" }],
  },
  {
    id: "pengintaian.is-scanned",
    branch: "pengintaian",
    depth: 2,
    name: "Sedang \"Scanned\"",
    summary: "Membaca apakah Scanner lawan sedang mengunci virus.",
    costData: 400,
    requires: ["pengintaian.ice-near"],
    unlocks: [{ kind: "condition", condition: "is-scanned" }],
  },
  {
    id: "pengintaian.took-damage-last-tick",
    branch: "pengintaian",
    depth: 2,
    name: "Baru Kena Damage",
    summary: "Membaca apakah virus kehilangan Integrity pada tick yang baru selesai.",
    costData: 400,
    requires: [],
    unlocks: [{ kind: "condition", condition: "took-damage-last-tick" }],
  },
  {
    id: "pengintaian.cloak-ready",
    branch: "pengintaian",
    depth: 2,
    name: "Cloak Siap",
    summary: "Membaca apakah Cloak tidak sedang aktif dan tidak sedang cooldown.",
    costData: 400,
    requires: [],
    unlocks: [{ kind: "condition", condition: "cloak-ready" }],
  },
  {
    id: "pengintaian.decoy-armed",
    branch: "pengintaian",
    depth: 2,
    name: "Decoy Terpasang",
    summary: "Membaca apakah masih ada serapan Decoy tersisa.",
    costData: 400,
    requires: [],
    unlocks: [{ kind: "condition", condition: "decoy-armed" }],
  },
  {
    id: "pengintaian.slowed",
    branch: "pengintaian",
    depth: 2,
    name: "Sedang Diperlambat",
    summary: "Membaca apakah efek Tarpit atau Slow Crawl sedang aktif.",
    costData: 400,
    requires: [],
    unlocks: [{ kind: "condition", condition: "slowed" }],
  },
  {
    id: "pengintaian.jammed",
    branch: "pengintaian",
    depth: 3,
    name: "Sensor Diacak",
    summary: "Membaca apakah sedang di dalam radius Jammer — satu-satunya cara mengetahui sensor lain sedang berbohong.",
    costData: 900,
    requires: ["pengintaian.scanner-near"],
    unlocks: [{ kind: "condition", condition: "jammed" }],
  },
  {
    id: "pengintaian.alarm-active",
    branch: "pengintaian",
    depth: 3,
    name: "Jaringan Siaga",
    summary: "Membaca apakah Alarm Relay lawan sedang aktif.",
    costData: 900,
    requires: [],
    unlocks: [{ kind: "condition", condition: "alarm-active" }],
  },
  {
    id: "pengintaian.tick-after",
    branch: "pengintaian",
    depth: 3,
    name: "Sudah Lewat X Tick",
    summary: "Membaca apakah tick battle sudah melewati sebuah angka.",
    costData: 900,
    requires: [],
    unlocks: [{ kind: "condition", condition: "tick-after" }],
  },
  {
    id: "pengintaian.every-n-ticks",
    branch: "pengintaian",
    depth: 3,
    name: "Tiap X Tick",
    summary: "Berdenyut tiap kelipatan tick tertentu — jadwal, bukan sekadar batas waktu.",
    costData: 900,
    requires: ["pengintaian.tick-after"],
    unlocks: [{ kind: "condition", condition: "every-n-ticks" }],
  },
  {
    id: "pengintaian.blocked-ahead",
    branch: "pengintaian",
    depth: 3,
    name: "Jalan di Depan Terhalang",
    summary: "Membaca apakah node di depan adalah Breach Node yang masih hidup.",
    costData: 900,
    requires: ["pengintaian.node-ahead-is"],
    unlocks: [{ kind: "condition", condition: "blocked-ahead" }],
  },
  {
    id: "pengintaian.move-avoiding-hazards",
    branch: "pengintaian",
    depth: 1,
    name: "Jalan Memutari Bahaya",
    summary: "Jalur terpendek yang menghindari node bahaya yang terlihat kondisi sensor di sheet ini.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "move-avoiding-hazards" }],
  },
  {
    id: "pengintaian.move-toward-node-type",
    branch: "pengintaian",
    depth: 2,
    name: "Buru Node Bertipe…",
    summary: "Jalur terpendek ke node hidup terdekat bertipe tertentu.",
    costData: 400,
    requires: ["pengintaian.move-avoiding-hazards"],
    unlocks: [{ kind: "action", action: "move-toward-node-type" }],
  },
  {
    id: "pengintaian.emp-burst.1",
    branch: "pengintaian",
    depth: 3,
    name: "EMP Tier I",
    summary: "Melumpuhkan semua node pendukung dalam radius untuk sementara.",
    costData: 900,
    requires: ["pengintaian.move-toward-node-type"],
    unlocks: [{ kind: "action", action: "emp-burst" }],
  },
  {
    id: "pengintaian.emp-burst.3",
    branch: "pengintaian",
    depth: 4,
    name: "EMP Tier III — capstone",
    summary: "Radius dan durasi lumpuh terbesar. Butuh pengalaman menembak presisi (Serbuan) untuk tahu node pendukung mana yang paling layak dilumpuhkan.",
    costData: 1800,
    requires: ["pengintaian.emp-burst.1", "serbuan.target-strike.1"],
    unlocks: [{ kind: "action", action: "emp-burst", tier: 3 }],
  },
  {
    id: "pengintaian.scanner.1",
    branch: "pengintaian",
    depth: 1,
    name: "Scanner Tier I",
    summary: "Aura: memberi status \"scanned\" (bonus akurasi ICE) pada virus dalam radius.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "scanner", tier: 1 }],
  },
  {
    id: "pengintaian.scanner.2",
    branch: "pengintaian",
    depth: 2,
    name: "Scanner Tier II",
    summary: "Radius dan durasi status scanned lebih besar.",
    costData: 400,
    requires: ["pengintaian.scanner.1"],
    unlocks: [{ kind: "defense-node", node: "scanner", tier: 2 }],
  },
  {
    id: "pengintaian.scanner.3",
    branch: "pengintaian",
    depth: 3,
    name: "Scanner Tier III",
    summary: "Bonus akurasi ICE tertinggi, juga menolkan bonus speed Slow Crawl.",
    costData: 900,
    requires: ["pengintaian.scanner.2"],
    unlocks: [{ kind: "defense-node", node: "scanner", tier: 3 }],
  },
  {
    id: "pengintaian.ice-sentry.1",
    branch: "pengintaian",
    depth: 1,
    name: "ICE Sentry Tier I",
    summary: "Menembak virus dalam radius tiap beberapa tick.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "ice-sentry", tier: 1 }],
  },
  {
    id: "pengintaian.ice-sentry.2",
    branch: "pengintaian",
    depth: 2,
    name: "ICE Sentry Tier II",
    summary: "Interval tembak lebih cepat, damage dan akurasi lebih tinggi.",
    costData: 400,
    requires: ["pengintaian.ice-sentry.1"],
    unlocks: [{ kind: "defense-node", node: "ice-sentry", tier: 2 }],
  },
  {
    id: "pengintaian.ice-sentry.3",
    branch: "pengintaian",
    depth: 3,
    name: "ICE Sentry Tier III",
    summary: "Radius terluas, damage dan akurasi tertinggi.",
    costData: 900,
    requires: ["pengintaian.ice-sentry.2"],
    unlocks: [{ kind: "defense-node", node: "ice-sentry", tier: 3 }],
  },
  {
    id: "pengintaian.jammer.1",
    branch: "pengintaian",
    depth: 1,
    name: "Jammer Tier I",
    summary: "Selagi virus di radius: semua kondisi sensor bernilai false.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "jammer", tier: 1 }],
  },
  {
    id: "pengintaian.jammer.2",
    branch: "pengintaian",
    depth: 2,
    name: "Jammer Tier II",
    summary: "Radius lebih luas.",
    costData: 400,
    requires: ["pengintaian.jammer.1"],
    unlocks: [{ kind: "defense-node", node: "jammer", tier: 2 }],
  },
  {
    id: "pengintaian.jammer.3",
    branch: "pengintaian",
    depth: 3,
    name: "Jammer Tier III",
    summary: "Juga memalsukan kondisi \"node di depan\".",
    costData: 900,
    requires: ["pengintaian.jammer.2"],
    unlocks: [{ kind: "defense-node", node: "jammer", tier: 3 }],
  },

  // --- Replikasi (biru) — multi-entitas & regenerasi ---
  {
    id: "replikasi.move-random",
    branch: "replikasi",
    depth: 1,
    name: "Jalan Acak",
    summary: "Edge acak dari node saat ini; tidak revisit kecuali buntu.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "move-random" }],
  },
  {
    id: "replikasi.is-clone",
    branch: "replikasi",
    depth: 1,
    name: "Aku Cabang",
    summary: "Membaca apakah tubuh ini lahir dari Worm Split, bukan entitas awal.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "is-clone" }],
  },
  {
    id: "replikasi.visited-here-before",
    branch: "replikasi",
    depth: 1,
    name: "Pernah Lewat Sini",
    summary: "Membaca apakah tubuh ini sudah pernah meninggalkan node ini sebelumnya.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "condition", condition: "visited-here-before" }],
  },
  {
    id: "replikasi.entity-count-below",
    branch: "replikasi",
    depth: 2,
    name: "Jumlah Cabang < X",
    summary: "Membaca jumlah tubuh yang masih hidup terhadap sebuah angka.",
    costData: 400,
    requires: ["replikasi.is-clone"],
    unlocks: [{ kind: "condition", condition: "entity-count-below" }],
  },
  {
    id: "replikasi.self-repair.1",
    branch: "replikasi",
    depth: 1,
    name: "Self Repair Tier I",
    summary: "Menambah Integrity per tick — syaratnya baris yang ditulis pemain sendiri.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "action", action: "self-repair" }],
  },
  {
    id: "replikasi.self-repair.3",
    branch: "replikasi",
    depth: 2,
    name: "Self Repair Tier III",
    summary: "Heal per tick tertinggi.",
    costData: 400,
    requires: ["replikasi.self-repair.1"],
    unlocks: [{ kind: "action", action: "self-repair", tier: 3 }],
  },
  {
    id: "replikasi.worm-split.1",
    branch: "replikasi",
    depth: 3,
    name: "Worm Split Tier I",
    summary: "Memecah virus jadi 2 tubuh yang berbagi sheet ini, masing-masing sebagian Integrity.",
    costData: 900,
    requires: ["replikasi.entity-count-below", "replikasi.self-repair.1"],
    unlocks: [{ kind: "action", action: "worm-split" }],
  },
  {
    id: "replikasi.worm-split.3",
    branch: "replikasi",
    depth: 4,
    name: "Worm Split Tier III — capstone",
    summary: "Sampai 3 tubuh hidup sekaligus, pembagian Integrity paling menguntungkan. Butuh titik respawn yang sudah ditandai (Bayangan) supaya sebuah cabang punya alasan bertahan.",
    costData: 1800,
    requires: ["replikasi.worm-split.1", "bayangan.set-checkpoint.1"],
    unlocks: [{ kind: "action", action: "worm-split", tier: 3 }],
  },
  {
    id: "replikasi.patch-server.1",
    branch: "replikasi",
    depth: 1,
    name: "Patch Server Tier I",
    summary: "Menyembuhkan Breach Node hidup dalam radius, tidak menyembuhkan dirinya sendiri.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "patch-server", tier: 1 }],
  },
  {
    id: "replikasi.patch-server.2",
    branch: "replikasi",
    depth: 2,
    name: "Patch Server Tier II",
    summary: "Heal per tick lebih besar.",
    costData: 400,
    requires: ["replikasi.patch-server.1"],
    unlocks: [{ kind: "defense-node", node: "patch-server", tier: 2 }],
  },
  {
    id: "replikasi.patch-server.3",
    branch: "replikasi",
    depth: 3,
    name: "Patch Server Tier III",
    summary: "Radius dan heal per tick tertinggi.",
    costData: 900,
    requires: ["replikasi.patch-server.2"],
    unlocks: [{ kind: "defense-node", node: "patch-server", tier: 3 }],
  },
  {
    id: "replikasi.turnstile.1",
    branch: "replikasi",
    depth: 1,
    name: "Turnstile Tier I",
    summary: "Node yang baru ditinggalkan tak bisa dikunjungi ulang untuk sementara.",
    costData: 150,
    requires: [],
    unlocks: [{ kind: "defense-node", node: "turnstile", tier: 1 }],
  },
  {
    id: "replikasi.turnstile.2",
    branch: "replikasi",
    depth: 2,
    name: "Turnstile Tier II",
    summary: "Lockout lebih lama.",
    costData: 400,
    requires: ["replikasi.turnstile.1"],
    unlocks: [{ kind: "defense-node", node: "turnstile", tier: 2 }],
  },
  {
    id: "replikasi.turnstile.3",
    branch: "replikasi",
    depth: 3,
    name: "Turnstile Tier III",
    summary: "Lockout terlama — rute memutar jadi keputusan permanen di battle itu.",
    costData: 900,
    requires: ["replikasi.turnstile.2"],
    unlocks: [{ kind: "defense-node", node: "turnstile", tier: 3 }],
  },
];
